baseURL = ""
languageCode = "en-us"
title = "devlog - Paulo Elienay"
disableKinds = ["section", "categories", "tags"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 9999
minify = true
disableHugoGeneratorInject = true


[taxonomies]
  tag = "tags"
  category = "categories"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
name = "Paulo Elienay"

[params]
description = "Logging the progress of personal projects"
author = "Paulo Elienay <paulo@pauloelienay.com>"
copyright = ""
logo = ""

[frontmatter]
date = [":filename", ":default"]
author = "Paulo Elienay"
github = "paulo-e"
facebook = ""
og_image = ""
sitename = "Paulo Elienay's Devlog"
twitter = "pauloelienay"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
[[menu.main]]
identifier = "index"
name = "index"
url = "/"
weight = -111

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = -30

[[menu.main]]
identifier = "about"
name = "about"
url = "https://pauloelienay.com"
weight = -20
